version: '3.1'
services:
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6479"

  vkr-db:
    image: postgres:14-alpine
    container_name: vkr-db
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=

  vkr-app:
    build: .
    image: main
    container_name: vkr-app
    ports:
      - "8080:8080"
    depends_on:
#      - redis
      - vkr-db
    environment:
      - DB_LINK=
      - DB_NAME=
      - DB_HOST=
      - DB_PORT=
      - DB_USER=
      - DB_PASSWORD=
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_REDIRECT_URI=